### ISSUE TITLE
Unknown query status: GATHERING RESULTS FROM SUBQUERIES

### ISSUE THREAD

**Issue by bschilt** [drutiny/sumologic#4]
When using subqueries in a policy, the sumologic API returns a query status that Drutiny is not expecting and throws the following message, leaving the policy in an error state:

SumoLogic returned unknown query status: GATHERING RESULTS FROM SUBQUERIES

Looking at the [status map](https://github.com/drutiny/sumologic/blob/2.x/src/Client.php#L27):

```
private $queryStatusMap = [
    'NOT STARTED'	=> self::QUERY_JOB_NOT_STARTED,
    'GATHERING RESULTS'	=> self::QUERY_JOB_IN_PROGRESS,
    'DONE GATHERING RESULTS'	=> self::QUERY_COMPLETE,
    'CANCELED'	=> self::QUERY_JOB_CANCELLED,
  ];
```

The `GATHERING RESULTS FROM SUBQUERIES` is not accounted for.

**Comment by bschilt** [comment]
I submitted PR https://github.com/drutiny/sumologic/pull/5.

**Comment by fiasco** [comment]
Merged. Thanks!
